# Generated by Django 3.2.8 on 2021-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211007_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('skills', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('startdate', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('gap', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('my_file', models.FileField(blank=True, upload_to='images')),
            ],
        ),
    ]
